baseurl = "https://zachsundwall.com/"
languageCode = "en-us"
languageLang = "en"
title = "Zach Sundwall"
author = "Zach Sundwall"
copyright = "Copyright © 2018, Zach Sundwall; all rights reserved."
canonifyurls = true
paginate = 3

theme = "hugograyscale"
